### ISSUE TITLE
Cluster ndmg data with Gaussian Mixture model, port U-ReRF to Python

### ISSUE THREAD

**Issue by karunkannan** [NeuroDataDesign/py-U-Rerf#6]
(Sprint 1)
goals:
1. Use scikit learn package to run Gaussian Mixture model on ndmg output
2. Port U-RerF to Python to allow for use of python packages down the road

**DoD**
- [ ] Run GMM on .edgelist files using features taken from NetworkX
- [ ] Run GMM on .edgelist files using features computed by @v715 
- [ ] Run Random Projection on HBN data
- [ ] Port over rfr_us.R methods to python
- [ ] Write proper documentation for methods
- [ ] Write unit tests and integration tests

**Comment by karunkannan** [comment]
`1. Process edgelists using Vivek's pipeline
2. Using this feature set, create K-fold stratification
3. For each fold, train GMM with different covariance type (‘full’, ‘tied’, ‘diag’, ‘spherical’)
4. Create plot similar to the one in slides for week 3 `

**Comment by jovo** [comment]
- two tasks
